// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uevszxptdjumfnbwpfku.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVldnN6eHB0ZGp1bWZuYndwZmt1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDIzODM1MjgsImV4cCI6MjA1Nzk1OTUyOH0.TXPlOuIE2qr8Oup0Q1WU-LopTnyas4dRlhiSyeRFDN0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);